spring:
  datasource:
    username: vyymeuga_ahmed
    password: Ahmed@123@123
    url: jdbc:mysql://solvenya.sd:3306/vyymeuga_mystore?useSSL=false&useLegacyDatetimeCode=false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true